apiVersion: v2
name: pedidos-app
description: Umbrella chart para la app de pedidos
type: application
version: 0.1.1
appVersion: "1.16.0"

dependencies:
  - name: backend
    version: 0.1.0
    repository: "file://charts/backend"    # ✅ Correcto desde raíz
  - name: frontend
    version: 0.1.0
    repository: "file://charts/frontend"   # ✅ Correcto desde raíz
  - name: postgresql
    version: 15.5.2
    repository: https://charts.bitnami.com/bitnami
    alias: db