backend:
  replicaCount: 1
  secretName: db-secret-dev
  configMapName: backend-db-config-dev
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"

frontend:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 8080
  resources:
    limits:
      cpu: "300m"
      memory: "256Mi"
    requests:
      cpu: "150m"
      memory: "128Mi"

db:
  auth:
    existingSecret: db-secret-dev
    username: devuser
    password: devpass
    database: devdb
    config:
      existingConfigMap: backend-db-config-dev
  primary:
    persistence:
      enabled: true
      storageClass: "do-block-storage"
      accessModes:
        - ReadWriteOnce
      size: 2Gi
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "250m"
        memory: "256Mi"

autoscaling:
  enabled: false  # en dev normalmente no escalamos

ingress:
  enabled: true
  rules:
    - host: dev.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: pedido-app-dev-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pedido-app-dev-frontend
                port:
                  number: 8080