replicaCount: 1

image:
  repository: 285juandm/frontend
  pullPolicy: Always
  tag: "1.0.1"

service:
  type: ClusterIP
  port: 8080

containerPort: 8080

ingress:
  enabled: false

resources:
    limits:
      cpu: "300m"
      memory: "256Mi"
    requests:
      cpu: "150m"
      memory: "128Mi"

# livenessProbe:
#   httpGet:
#     path: /
#     port: http
# readinessProbe:
#   httpGet:
#     path: /
#     port: http
