apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  postgres-password: bXlwYXNz      # contraseña del superusuario postgres
  username: bXl1c2Vy               # usuario normal
  password: bXlwYXNzd29yZA==       # contraseña del usuario normal
  database: bXlkYg==               # base de datos a crear
