{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "pedidos-app.fullname" . }}
  labels:
    {{- include "pedidos-app.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- if .Values.ingress.rules }}
      {{- range .Values.ingress.rules }}
      - http:
          paths:
            {{- range .http.paths }}
            - path: {{ .path }}
              pathType: {{ .pathType | default "ImplementationSpecific" }}
              backend:
                service:
                  name: {{ .backend.service.name }}
                  port:
                    number: {{ .backend.service.port.number }}
            {{- end }}
      {{- end }}
    {{- else if .Values.ingress.hosts }}
      {{- range .Values.ingress.hosts }}
      - host: {{ .host | quote }}
        http:
          paths:
            {{- range .paths }}
            - path: {{ .path }}
              pathType: {{ .pathType | default "ImplementationSpecific" }}
              backend:
                service:
                  name: {{ .backend.service.name }}
                  port:
                    number: {{ .backend.service.port.number }}
            {{- end }}
      {{- end }}
    {{- end }}
{{- end }}
